# Generated by Django 3.1.14 on 2021-12-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('image', models.ImageField(upload_to='images', verbose_name='images')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='thumbnail')),
                ('skill', models.CharField(max_length=100, verbose_name='skill')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='url')),
                ('created', models.DateField(verbose_name='Created date')),
                ('description', models.TextField(verbose_name='explanation')),
            ],
        ),
    ]
