# Generated by Django 3.1.14 on 2021-12-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_softwere_technical'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Software')),
                ('level', models.CharField(max_length=100, verbose_name='Level')),
                ('percentage', models.IntegerField(verbose_name='Percentage')),
            ],
        ),
        migrations.DeleteModel(
            name='Softwere',
        ),
        migrations.AlterField(
            model_name='technical',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Technical'),
        ),
    ]
